project_id = "wvpuwmzjeluiwilgbutd"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
# the first email gets path /monitor/1, second one gets /monitor/2, etc.
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327

[functions.twitter-monitor]
verify_jwt = false

[functions.analyze-sentiment]
verify_jwt = false