// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvpuwmzjeluiwilgbutd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2cHV3bXpqZWx1aXdpbGdidXRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMjc1NjgsImV4cCI6MjA3MDcwMzU2OH0.ghe1Buvao_UabXX83KsnZmx3KRJcJlo2YO6SaZimRsk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});